### PR TITLE
BFW-2542 PVB disappeared from preheat and filament menu

### PR DESCRIPTION
**Pull request by zoltan-l**

### CODE REVIEW

**Review by vorner — COMMENTED** [review]
Mostly looks fine. However, the filaments got reordered. Is that OK?

What I worry about is, if someone upgrades the firmware, the eeprom contains the currently loaded filament as a number ‒ and if they get reordered, the printer might get confused and mismatch them. It's not a very big deal if that happens, so if there's a good reason to reorder them, then this is fine I think.

**Comment by zoltan-l** [comment]
It is not reordering it is reinstallment the original order destroyed by some changes. Now it is coherent with the 4.3.4 filament order

**Comment by zoltan-l** [comment]
Based on Radek review and recomendations changed the identical definitions by macro

**Review by RadekVana — APPROVED** [review]

**Comment by DRracer** [comment]
The order of filament is correct (matches the previous state defined in BFW-1661)

**Pull request merged**
