### PR TITLE
[BFW-5530] gui: Fix german language issue with Filament Color layout and First setup

### PR DESCRIPTION
**Pull request by bkerler**
Fix german language issue with Filament Color layout, related to issue #3611 and First setup screen.

The filament color change screen before:
image

Now:
image

The setup wizard screen was modified as well to fix the broken display layout.

Previous setup wizard:
image

Now:
image

### CODE REVIEW

**Comment by Hayajiro** [comment]
I'd love seeing this getting merged (the members of our FabLab are joking about this), but I guess one reason why this has been lying around since December is the incorrect commit history. Instead of rebasing your changes with master, you merged master your branch, resulting in duplicate commits.

**Comment by bkerler** [comment]
@Hayajiro I normally always base against master, but it was a decision to base against v5.1.2 by one of the Prusa Developers. GUI changes have to go through several departments, that's why it is taking quite long.

**Review by danopernis — APPROVED** [review]

**Comment by marcel151** [comment]
Why the "Plenk" (blank before the question mark), though? Please, that looks just stupid and other than that, its wrong.

**Comment by foorschtbar** [comment]
> Why the "[Plenk](https://de.m.wikipedia.org/wiki/Plenk)" (blank before the question mark), though? Please, that looks just stupid and other than that, it's wrong.

Not stupid - thats a hard word! - but wrong. PR with fix is opened https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/4136 :)

**Comment by marcel151** [comment]
> > Why the "[Plenk](https://de.m.wikipedia.org/wiki/Plenk)" (blank before the question mark), though? Please, that looks just stupid and other than that, it's wrong.
> 
> Not stupid - thats a hard word! - but wrong. PR with fix is opened #4136 :)
That's what I (also) said. ;-) It always looks stupid for me, sorry if I'm that harsh. I never understand why people do that. It's more work (you have to press space), it looks unpleasant and for the most part, it's wrong. Maybe somebody knows why people do it.
Thank you for the PR.

**Pull request merged**
