### PR TITLE
gui: Fix wrong temp display in preheat menu, add new preheat menu

### PR DESCRIPTION
**Pull request by bkerler**
Fix missing separation between preheating and filament load/unload leading to wrong ui information, displaying nozzle temperature for the "preheat" menu instead of the nozzle_preheat temperature.

Adds a new preheat menu for preheating heat and bed (displaying nozzle temp of nozzle_preheat correctly which was display wrong before), heating up nozzle to target temp (according to selected filament nozzle temp) and heating up only heatbed to preheat temperature separately.

Avoids confusion and makes maintenance easier (nozzle change, cleaning etc.).

Related to issues #3708, #1795.

image

image

### CODE REVIEW

**Comment by murk-sy** [comment]
I still think the modified preheat menu should display the temperatures, and ideally, the loaded material - see original feature request. Maybe having them listed right-aligned like in material selection would make sense. Ideally in a way so that the slashes are aligned.

I'm not sure if what I used would be the best terminology since the space is limited, but not including the temperatures makes it also confusing (but in the other direction compared to before).

**Comment by vorner** [comment]
Internal reference: BFW-5040

**Comment by CZDanol** [comment]
Hey, we've consulted this in the company and decided to extend your proposal with a bit more functionality. So - we will implement something quite similar to this, but we need to develop it internally. Also, the preheat menu has already been refactored, so this PR is not mergeable anymore.

So I'm closing this PR. Thank you for your work and sorry that it hasn't been taken as-is.

**Comment by bkerler** [comment]
@CZDanol No worries, at least it was helpful in terms of "inspiration" :D

**Pull request closed without merging**
