### PR TITLE
variant8_t C++ implementation

### PR DESCRIPTION
**Pull request by marekmosna-prusa3d**
BFW-1253

### CODE REVIEW

**Comment by mkbel** [comment]
I am too lazy to read the code. Can you write some summary (or philosophy behind) of what is changed and why? Also I am big opponent of having dynamic memory allocation in time critical embedded software. Is this aspect of variant8_t somehow improved? (e.g. not allocating at least small types on heap)

**Comment by marekmosna-prusa3d** [comment]
> I am too lazy to read the code. Can you write some summary (or philosophy behind) of what is changed and why? Also I am big opponent of having dynamic memory allocation in time critical embedded software. Is this aspect of variant8_t somehow improved? (e.g. not allocating at least small types on heap)

OK, I'll try. 
Short versions of the answers are:
* it changes entire C implementation
* I got the task to make C++ version
* up to 7 characters string  can be passed by the variant without any allocation as an user type

Philosophy is not such a straight. Basic visions are:
* as less code as possible => easy to maintain
* strongly typed implementation
* focused on minimize reinterpret casts

I hope it helps as a brief introduction

**Review by espr14 — APPROVED** [review]

**Review by DRracer — COMMENTED** [review]
So far the biggest problem with variant (C-style) was the fact, that variants holding pointers didn't carry any information whether the memory pointed to is owned by the variant or not.
From that arose serious issues like duplicit deallocation attempts or memory leaking.
I don't see any improvement in this solution, even though I like the enable_if construct.

**Comment by espr14** [comment]
> So far the biggest problem with variant (C-style) was the fact, that variants holding pointers didn't carry any information whether the memory pointed to is owned by the variant or not.
> From that arose serious issues like duplicit deallocation attempts or memory leaking.
> I don't see any improvement in this solution, even though I like the enable_if construct.

Duplicit deallocation can be avoided with these steps:
- set pointer to nullptr after deallocation
- avoid deallocating of nullptr
- thread safe deallocation

To define ownership of the data you can add a single bit flag.

**Pull request closed without merging**
