### PR TITLE
ESP: fix broken FW version

### PR DESCRIPTION
**Pull request by laloch**
Fixes the previous commit, where I somehow managed to commit some ESP firmware binary of unknown origin and unknown quality. Sorry folks.

### CODE REVIEW

**Review by DRracer — COMMENTED** [review]
:thinking: how am I supposed to verify the binary file? Do we need this for #2206?

**Comment by laloch** [comment]
@DRracer, yes you are completely right. We need to automate the process and make sure that this faux pas will never happen again.

**Review by vorner — APPROVED** [review]
I don't think we are able to verify it right now or come up with proper automation. On the other hand, we need it to reflect the reality. Let's rely on testing, but we should start talking about the automation soon-ish.

Especially because this is not the only stuff with this issue, the PrusaLink content is similar ‒ manually built and commited :-(.

**Comment by laloch** [comment]
This has been already merged in scope of #2206.

**Pull request closed without merging**
