### PR TITLE
Avoid global python package installs in bootstrap

### PR DESCRIPTION
**Pull request by vladamatena**
Add --user to install commandline to avoid breaking system packages.

### CODE REVIEW

**Comment by vorner** [comment]
Will this work OK with my setup of using virtualenv setup? I use that one instead, I don't want it to break my _user_ packages either 😇

**Comment by vladamatena** [comment]
> Will this work OK with my setup of using virtualenv setup? I use that one instead, I don't want it to break my _user_ packages either innocent
Good point, it will refuse to install for virtualenv. I will look for better solution.

**Comment by dragomirecky** [comment]
I think the best option would be to create custom virtualenv automatically (and run everything within that virtualenv). 
I have this as a todo for some time in my head but didn't get to it yet

**Comment by danopernis** [comment]
Since we are using `venv` now, this can be closed.

**Pull request closed without merging**
