### PR TITLE
configuration: Correct the Max Temperature for Prusa Mini

### PR DESCRIPTION
**Pull request by bkerler**
Lower the Max Temp safety margin for Prusa Mini in order to reach advertised nozzle temp of 280°C, related to issue #3489 and #3605.

### CODE REVIEW

**Comment by danopernis** [comment]
Proposed solution is simple, but it may be dangerous. We should properly test this. The general consensus is that the current MINI temperature controller should be an improvement to the original PID controller and should be able to regulate temperature, so the fix should work.

Proposed testing scenario (thanks @mkbel)
* Start with cold extruder, request maximum temperature (280°C, with this patch)
* Check that we do not overshoot near 290°C
  * Overshooting to 287°C (temporarily) is OK, anything more is NOK
* Now the extruder reached 280°C
* Gradually increase print fan speed until temperature starts dropping
* Stop the print fan
* Check that we do not overshoot near 290°C
  * Overshooting to 287°C (temporarily) is OK, anything more is NOK

**Comment by bkerler** [comment]
Yes, fully agree. It's a safety functionality, so intense testing is needed. If 10 cannot be reached as safety margin (with allowance for 280), and 15 has to stay as safety margin, then the sales description has to be corrected to 275°C asap. Or an option for allowance is going to be added that the user is accepting that there will be no warranty for the extruder or parts of the extruder if the safety margin is set to 10.

**Comment by kozross** [comment]
> Proposed solution is simple, but it may be dangerous. We should properly test this. The general consensus is that the current MINI temperature controller should be an improvement to the original PID controller and should be able to regulate temperature, so the fix should work.
> 
> Proposed testing scenario (thanks @mkbel)
> 
>     * Start with cold extruder, request maximum temperature (280°C, with this patch)
> 
>     * Check that we do not overshoot near 290°C
>       
>       * Overshooting to 287°C (temporarily) is OK, anything more is NOK
> 
>     * Now the extruder reached 280°C
> 
>     * Gradually increase print fan speed until temperature starts dropping
> 
>     * Stop the print fan
> 
>     * Check that we do not overshoot near 290°C
>       
>       * Overshooting to 287°C (temporarily) is OK, anything more is NOK

Is this the official word from Prusa? Because if so, I would _love_ to know how this problem stood quiescent for nearly _four years_, and then got dropped on our heads with nary a word of announcement. If there were indeed safety concerns, these should have been announced, broadly and clearly, with an explanation of what fix has been undertaken, in detail, not smuggled in amid a bunch of other unrelated changes with nary a word.

I'd also like to add that, if indeed the Mini cannot sustain max temperatures of 280C, then the product I've been sold no longer meets the specifications it is supposed to, and some compensation is in order. I've literally paid for a feature I can no longer use.

**Comment by danopernis** [comment]
Let's not be overly dramatic here. I will try to explain how we got there. Bear in mind that I am nobody official, just a developer trying his best here, hoping that his openness and honesty will be appreciated.

During the development of MK4 firmware we stumbled upon the inconsistency in setting of the safety margins and maximum temperatures. At that point in time, we were sure we are not releasing new firmware for MINI any time soon. To stay on the safe side, we went with increasing the safety margin. This change apparently introduced the bug and ended up in MINI release later, where it affects you.

Please be mindful that this is a bug we are trying to fix and I am trying to be honest about it. Proposed fix is very likely sufficient. I am just trying to be extra careful here, given the opportunity to properly test this.

I am pretty confident this will be eventually fixed in future release. In the meantime, if you absolutely need to print with these temperatures before we get this sorted out, I suggest using the older firmware. Harassing the developers online is not going to bring you that fix any sooner.

For the official word from Prusa, I suggest contacting the support.

**Comment by parsingphase** [comment]
It is hard to see this polite, if frustrated, complaint as either "overly dramatic" or "hassling the developers". Admittedly, no developer likes seeing problems with their work or company discussed in public. However, given that this selfsame company explicitly makes its code and issue trackers public, that is where the discussion has to take place, and I would personally be very happy if the last 30 years' complaints about my own work had all been phrased with such restraint as this.

**Comment by bkerler** [comment]
Please keep discussions in the issues, not in the PR, people. It's already hard to keep track of PRs. 

Do keep in mind it's not like we're not trying to find an acceptable solution for you MINI owners (I don't even own a Mini, but still pushed some fixes for it, btw. and I'm doing it in my spare time).

**Comment by e-dreyer** [comment]
I think some transparency is required here. Mini users are not able to rune their own PID autotune or set it easily. These PID values determine the rate of the heating as well as the max temperature. 

The printer's actual "allowed printing temperature by Prusa" is different from the "actual advertised printing temperature by Prusa". What is the reason for this?

Currently, the topic is being evaded, shunned and kept on the down low. I am starting to think, in order to bring the printer's price down, Prusa cheaped out on the power supply. 150W! Which is just pure insanity. 

Is the Mini not able to achieve this max temperture safely due to the actual construction of the hotend, such as materials possibly melting, or can you not heat it safely with the stock power supply? So now you are blind siding us and make us feel as if we are wearing tin foil hats. Explain why we can't heat our printers to the temperature that you advertised and that we bought it for. If I bought the printer for that specific temperature, I cannot use it for my use case.

Did the specification change during the design phase and you did not update it, or were you not able to achieve it and chose to lie to us?

Bambu stole a lot from Prusa, but damn, you guys are now stealing false advertising and shady business practices from their playbook.

**Comment by bkerler** [comment]
@e-dreyer This isn't a discussion board here, it's a pull request. PID autotune isn't even related to this pull request. If you want a discussion, there's a forum for that. Thanks.

**Comment by danopernis** [comment]
@bkerler I have run some tests on MINI and did some digging in the code history. Looks like there was a bug introduced when adjusting the code to be in sync with the spec. I did not observe any problems with thermal regulation when maintaining those 280C with various print fan speeds, so we should be safe here.

Can you please update the PR accordingly? Max temp should be 295 and safety margin should be 15, giving the maximum of 280 in accordance with the spec.

Also, let's remove the PA from the menu in separate PR in order to not clutter this already cluttered PR. Thanks :pray:

**Comment by bkerler** [comment]
Sure, that's great ! Let's have a look

**Comment by bkerler** [comment]
Done :)

**Pull request closed without merging**
