### PR TITLE
mbedtls integration

### PR DESCRIPTION
**Pull request by marekmosna-prusa3d**
* mbedTLS v2.26.0

BFW-1788

### CODE REVIEW

**Review by joshymjose — CHANGES_REQUESTED** [review]
let's merge after a successful test

**Review by joshymjose — CHANGES_REQUESTED** [review]
changing the CMake files in SSL library is not a good idea

This PR does things other than ssl integration like change of wui structure which should be done in a different PR after some discussions

I cannot completely agree with the structure of integration test

**Comment by vladamatena** [comment]
1. I managed to build this. First attempt ended up in linking failure (no idea why), all subsequent attempts are a success. Still, it complains about implicit declaration.

```
vlada@fuji ~/Prusa-Firmware-Buddy $ .dependencies/ninja-1.9.0/ninja all -C build/ssl-tests/
ninja: Entering directory `build/ssl-tests/'
[258/464] MbedTLS v2.26.0 relase build
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components:  Interpreter 
-- The C compiler identification is GNU 7.3.1
-- Check for working C compiler: /home/vlada/Prusa-Firmware-Buddy/.dependencies/gcc-arm-none-eabi-7.3.1/bin/arm-none-eabi-gcc
-- Check for working C compiler: /home/vlada/Prusa-Firmware-Buddy/.dependencies/gcc-arm-none-eabi-7.3.1/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- Additional compile options: -DMBEDTLS_CONFIG_FILE=</home/vlada/Prusa-Firmware-Buddy/lib/WUI/../../include/mbedtls_config.h>;-mthumb;-mcpu=cortex-m4;-mfloat-abi=hard;-mfpu=fpv4-sp-d16
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vlada/Prusa-Firmware-Buddy/build/ssl-tests/lib/mbedtls-release
[92/92] Linking C static library mbedtls/library/libmbedtls.a
[305/464] Building C object CMakeFiles/firmware.dir/home/vlada/Prusa-Firmware-Buddy/src/common/dbg.c.obj
/home/vlada/Prusa-Firmware-Buddy/src/common/dbg.c: In function '_dbg_swo':
/home/vlada/Prusa-Firmware-Buddy/src/common/dbg.c:53:15: warning: implicit declaration of function 'vsnprintf' [-Wimplicit-function-declaration]
     int len = vsnprintf(line, DBG_MAXLINE, fmt, va);
               ^~~~~~~~~
[464/464] Linking CXX executable firmware

   text    data     bss     dec     hex filename
 337328    2844   56592  396764   60ddc /home/vlada/Prusa-Firmware-Buddy/build/ssl-tests/firmware
```

2. Maybe I am doing something wrong but the resulting application does not seem to do anything. The StartsslTask does not seem to be executed:
```
vlada@fuji ~/Prusa-Firmware-Buddy $ grep -R StartsslTask
tests/integration/ssl/mbedtls.c:void StartsslTask(void const *argument) {
tests/integration/ssl/mbedtls.h:void StartsslTask(void const *argument);
lib/WUI/wui.c:extern void StartsslTask();
build/ssl-tests/firmware.map: .text.StartsslTask
build/ssl-tests/firmware.map: .rodata.StartsslTask.str1.4
```
The SWO output is suspiciously short:
```
[2021-06-09T10:47:07.866Z]   app_run
```

3. Maybe the instructions on how to build and run the integration test should be part of the repository. I admin I am still a bit puzzled while looking into the sources. Maybe you can instruct the cmake to setup the test with ease, but still it might be useful for newcomers.

4. This is a bit general remark. The mbedtls integration does not use git submodule, but rather includes a copy of mbedtls sources. I can see this is the case for all the integrated third party tools. Still, I can only see downsides of this approach (difficult to maintain differences to upstream, difficult to even see differences to upstream, difficult to integrate upstream changes, heavier repository, difficult to push fixes to upstream)

5. I agree with Joshy that introducing an integration test infrastructure and 1K+ news files in a single PR is not the best idea.

6. Regarding the structure, I agree we can live with raw copy of CMake and separate the parts common for multiple integration tests once we know what parts actually differ. On the other hand, also the main.cpp is a raw copy with only subtle changes that can be pushed to separate file easily.

7. Another general remark, where does the mbedtls (or the external libraries in general) belong?
- lib/Middlewares/Third_Party/
- lib/Middlewares
- lib

Feel free to ignore all the remarks, you know your code better than me. On the other hand, no. 2 may be worth some attention as I think something is broken so that the integration test does not execute.

**Review by joshymjose — CHANGES_REQUESTED** [review]
@vladamatena 
Regarding the your point (4), FW team uses the subrepo. But I think nobody does the update properly.

Till now the external libraries are added under /lib

This could be divided into multiple PRs 
1. with basic test infrastructure
2. mbedtls addition 
3. test ssl appplication

Sure there should be some readme about the structure of the Integration test and how to run them

**Pull request closed without merging**
